/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.magonono.wandapi;

import com.magonono.wandapi.controller.WandApiController;
import com.magonono.wandapi.log.LogManager;
import com.magonono.wandapi.view.Beautifier;
import javax.swing.text.*;
import java.awt.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 * Created for the WandApi project.
 *
 * @author Cesar "Aran" Pasillas
 */
public class WandApiFrame extends javax.swing.JFrame {

    WandApiController wandApiController = new WandApiController();
    
    LogManager log;
    DefaultListModel<String> historyListModel;

    /**
     * Creates new form WandApiFrame
     */
    public WandApiFrame() {
        loadHistoryList();
        initComponents();
        log = new LogManager("WandApi");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Historial = new javax.swing.JPanel();
        historyLabel = new javax.swing.JLabel();
        historyScrollPane = new javax.swing.JScrollPane();
        historyList = new javax.swing.JList<>();
        historySeparator = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        main = new javax.swing.JPanel();
        httpMethodsComboBox = new javax.swing.JComboBox<>();
        urlTextInput = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTextPane = new javax.swing.JTextPane();
        statusCodeLabel = new javax.swing.JLabel();
        responseCodeLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        responseTextPane = new javax.swing.JTextPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextPane();
        requestLabel = new javax.swing.JLabel();
        requestLabel1 = new javax.swing.JLabel();
        requestLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Historial.setBackground(new java.awt.Color(255, 255, 255));

        historyLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        historyLabel.setForeground(new java.awt.Color(102, 102, 255));
        historyLabel.setText("History");

        historyList.setBackground(new java.awt.Color(102, 102, 255));
        historyList.setForeground(new java.awt.Color(255, 255, 255));
        historyList.setModel(historyListModel);
        historyScrollPane.setViewportView(historyList);

        historySeparator.setBackground(new java.awt.Color(204, 204, 255));
        historySeparator.setForeground(new java.awt.Color(204, 204, 255));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HistorialLayout = new javax.swing.GroupLayout(Historial);
        Historial.setLayout(HistorialLayout);
        HistorialLayout.setHorizontalGroup(
            HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(historySeparator)
                    .addGroup(HistorialLayout.createSequentialGroup()
                        .addGroup(HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(historyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(historyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HistorialLayout.setVerticalGroup(
            HistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistorialLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(historyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historySeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        Background.add(Historial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 340, 740));

        main.setBackground(new java.awt.Color(204, 204, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        httpMethodsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GET", "POST", "DELETE", "PUT", "PATCH" }));
        httpMethodsComboBox.setToolTipText("Http Method");
        httpMethodsComboBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        httpMethodsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                httpMethodsComboBoxActionPerformed(evt);
            }
        });
        main.add(httpMethodsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        urlTextInput.setText("https://api.thecatapi.com/v1/images/search");
        urlTextInput.setToolTipText("");
        main.add(urlTextInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 520, 30));

        sendButton.setBackground(new java.awt.Color(102, 102, 255));
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setText("Send");
        sendButton.setToolTipText("Button to send the request");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        main.add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 90, 30));

        jScrollPane2.setViewportView(requestTextPane);

        main.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 690, 240));

        statusCodeLabel.setText("Status Code:");
        main.add(statusCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        responseCodeLabel.setForeground(new java.awt.Color(0, 153, 51));
        responseCodeLabel.setText("200");
        main.add(responseCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        responseTextPane.setEditable(false);
        responseTextPane.setBackground(new java.awt.Color(255, 255, 255));
        StyledDocument doc = responseTextPane.getStyledDocument();

        // Create key and value styles
        Style keyStyle = responseTextPane.addStyle("KeyStyle", null);
        StyleConstants.setForeground(keyStyle, Color.RED);  // Keys in red

        Style valueStyle = responseTextPane.addStyle("ValueStyle", null);
        StyleConstants.setForeground(valueStyle, Color.GREEN);
        jScrollPane3.setViewportView(responseTextPane);

        main.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 690, 220));

        jToggleButton1.setText("Activate Beautify");
        jToggleButton1.setToolTipText("Activates the JSON Beautification");
        main.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        console.setEditable(false);
        console.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(console);

        main.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 690, 100));

        requestLabel.setText("Output:");
        main.add(requestLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        requestLabel1.setText("Request:");
        main.add(requestLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        requestLabel2.setText("Response:");
        main.add(requestLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        Background.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 6, 720, 750));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        Beautifier beautifier = new Beautifier(responseTextPane);
        System.out.println(urlTextInput.getText());
        String url = urlTextInput.getText();
        String json = wandApiController.sendRequest(urlTextInput.getText(),
            (String) httpMethodsComboBox.getSelectedItem());

        String httpMethod = (String) httpMethodsComboBox.getSelectedItem();

        StyledDocument consoleStyle = console.getStyledDocument();

        Style consoleTextStyle = console.addStyle("consoleTextStyle", null);
        StyleConstants.setForeground(consoleTextStyle, Color.BLACK);

        try {
            consoleStyle.insertString(consoleStyle.getLength(), log.logInfo(" " +httpMethod +": " + url) +"\n", consoleTextStyle);
        } catch (BadLocationException ex) {
            Logger.getLogger(WandApiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        log.logInfo("GET: " + url);

        responseTextPane.setText(""); //Clear before send any response.

        responseTextPane.setText(wandApiController.sendApiRequest(urlTextInput.getText(), httpMethod));
        
        //send to the historial
        //historyList.getSelectedValue()
        
        historyListModel.addElement(httpMethod + " " + url);
        //lstHistoryList.(httpMethod + " " + url);
    }//GEN-LAST:event_sendButtonActionPerformed

    private void httpMethodsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_httpMethodsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_httpMethodsComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WandApiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WandApiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WandApiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WandApiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WandApiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Historial;
    private javax.swing.JTextPane console;
    private javax.swing.JLabel historyLabel;
    private javax.swing.JList<String> historyList;
    private javax.swing.JScrollPane historyScrollPane;
    private javax.swing.JSeparator historySeparator;
    private javax.swing.JComboBox<String> httpMethodsComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel main;
    private javax.swing.JLabel requestLabel;
    private javax.swing.JLabel requestLabel1;
    private javax.swing.JLabel requestLabel2;
    private javax.swing.JTextPane requestTextPane;
    private javax.swing.JLabel responseCodeLabel;
    private javax.swing.JTextPane responseTextPane;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel statusCodeLabel;
    private javax.swing.JTextField urlTextInput;
    // End of variables declaration//GEN-END:variables

    private void loadHistoryList() {
        
        historyListModel = new DefaultListModel<>();
        
    }
}
